version: '3.8'

services:
  db:
    image: postgres:15
    container_name: imtracker_db_prod
    environment:
      - POSTGRES_DB=imtracker
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  web:
    build: .
    container_name: imtracker_web_prod
    command: gunicorn IncidenciasApp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=imtracker
      - DB_USER=${DB_USER:-imtracker_user}
      - DB_PASSWORD=${DB_PASSWORD:-imtracker_pass}
      - DJANGO_SETTINGS_MODULE=IncidenciasApp.settings
    depends_on:
      - db

  n8n:
    image: n8nio/n8n:latest
    container_name: imtracker_n8n_prod
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
    volumes:
      - n8n_data_prod:/home/node/.n8n

volumes:
  n8n_data_prod:
  postgres_data_prod:
