"""
Django settings for IncidenciasApp project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# He importado gettext_lazy para poder marcar los nombres de los idiomas (Español/English) para su traducción
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a+)4#pwx)z8l1bmn2@xa1n=!l@_xl)m@zi@bp0j60g97k^apu-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'incidencias',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

AUTH_USER_MODEL = 'incidencias.UsuarioPersonalizado'  #le indica a Django que, en lugar de usar el modelo de usuario predeterminado, debe utilizar el modelo personalizado de usuario definido en tu aplicación incidencias (en este caso, UsuarioPersonalizado)


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # He añadido LocaleMiddleware justo después del SessionMiddleware para que Django reconozca el idioma del usuario
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'IncidenciasApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # He añadido este context processor para que la variable LANGUAGE_CODE esté disponible en mis plantillas HTML
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'IncidenciasApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DB_NAME', 'imtracker'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'imtracker_super_secreta_2026'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# He configurado el idioma por defecto a 'es' en formato corto
LANGUAGE_CODE = 'es'

# He definido los dos idiomas que voy a soportar en el proyecto: Español e Inglés
LANGUAGES = [
    ('es', _('Español')),
    ('en', _('English')),
]

# He indicado la carpeta donde guardaré los archivos .po y .mo con las traducciones
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'incidencias/static'),
]

# Configuración de Correo Electrónico
# Usamos Gmail SMTP para enviar correos reales
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'soporte.imtracker@gmail.com'
EMAIL_HOST_PASSWORD = 'lrwj xqzc lete rxbe'
DEFAULT_FROM_EMAIL = 'IMTracker Soporte <soporte.imtracker@gmail.com>'

# Configuración de URLs de autenticación
LOGIN_URL = 'incidencias:login'
LOGIN_REDIRECT_URL = 'incidencias:dashboard'
LOGOUT_REDIRECT_URL = 'incidencias:login'



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Para la carga de imagenes en las incidencias
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# La configuración SMTP ya está definida arriba.


# =============================================================================
# FICHEROS DE LOGS
# =============================================================================
# Configuración del sistema de logging de Django.
# Se generan 3 ficheros de log dentro de la carpeta 'logs/' del proyecto:
#   - django_general.log  → Errores y warnings de toda la aplicación
#   - django_security.log → Intentos de login, cambios de contraseña, CSRF, etc.
#   - django_requests.log → Peticiones HTTP (solo errores 4xx y 5xx)

# Creamos la carpeta 'logs/' automáticamente si no existe
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # Formateadores: definen cómo se escribe cada línea en el fichero
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module}.{funcName}:{lineno} → {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{asctime}] {levelname} → {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },

    # Handlers: destinos donde se escriben los logs
    'handlers': {
        # Consola (para desarrollo, muestra los mensajes en el terminal de Docker)
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        # Fichero de errores generales de la aplicación
        'file_general': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'django_general.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Fichero de seguridad (login, logout, CSRF, permisos)
        'file_security': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'django_security.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Fichero de peticiones HTTP con error (4xx, 5xx)
        'file_requests': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'django_requests.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },

    # Loggers: categorías que capturan los eventos
    'loggers': {
        # Logger principal de Django
        'django': {
            'handlers': ['console', 'file_general'],
            'level': 'WARNING',
            'propagate': True,
        },
        # Logger de seguridad (intentos de login fallidos, CSRF, etc.)
        'django.security': {
            'handlers': ['file_security'],
            'level': 'INFO',
            'propagate': False,
        },
        # Logger de peticiones HTTP
        'django.request': {
            'handlers': ['file_requests'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Logger personalizado para nuestra app 'incidencias'
        'incidencias': {
            'handlers': ['console', 'file_general'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}