upstream web_app {
    server web:8000;
}

server {
    listen 80;
    server_name imtracker.nachodaw.com;

    # Para el reto de Certbot (Validación de SSL)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirección permanente a HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name imtracker.nachodaw.com;

    ssl_certificate /etc/letsencrypt/live/imtracker.nachodaw.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/imtracker.nachodaw.com/privkey.pem;

    # Configuraciones de seguridad SSL recomendadas
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Proxy a la app de Django
    location / {
        proxy_pass http://web_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Servir archivos estáticos directamente desde Nginx
    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }
}
