# Generated by Django 5.2 on 2025-05-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='departamento',
            field=models.CharField(blank=True, choices=[('compras', 'Compras'), ('ventas', 'Ventas'), ('it', 'IT'), ('manager', 'Manager IT')], max_length=20, null=True),
        ),
    ]
