# Generated by Django 6.0.4 on 2026-05-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_alter_usuariopersonalizado_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='prioridad_sugerida_ia',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='resumen_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
